apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
  namespace: cyberlearn
type: Opaque
stringData:
  POSTGRES_DB: shopdb
  POSTGRES_USER: cyberlearn
  POSTGRES_PASSWORD: StrongPassword_ChangeMe
